### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by frewsxcv** [ethereum/pyethereum#132]

**Comment by adamkrellenstein** [comment]
Isn't pybitcointools another Python 2-only dependency?

**Comment by vbuterin** [comment]
It's actually py3-friendly now.
On Feb 18, 2015 4:41 AM, Adam Krellenstein <notifications@github.com> wrote:Isn't pybitcointools another Python 2-only dependency?

**Comment by adamkrellenstein** [comment]
Hi, just wanted to let you guys know that @ouziel-slama and I are working on adding Python 3 support to pyethereum (and ethereum-serpent and rlp), so that we can use it (the VM, specifically) in https://github.com/CounterpartyXCP/counterpartyd. We've made some progress already, but we'd like to pass as many tests with our fork as possible, so that you guys are inclined to merge the patch upstream.

I guess the big question for us is do you want to preserve support for Python 2? Of course, I'm a big Py3k fan and would love to let Python 2 finally die ;), but it's up to you (and I'm not yet sure how much work it'll be to support both). @vbuterin?

Anyway, watch out for pull requests from us.

**Comment by vbuterin** [comment]
Hmm, lots of people have asked and it's a complicated question. In what
portion of new mac/linux distros is python3 available by default? If it's a
substantial majority, then I'll be fine moving over.

**Comment by ouziel-slama** [comment]
IMO, in what portion of distros is python3 available should not be a decisive element. For end users, an "freeze" distribution with an installer should be available, else, with Python 2 or 3, they don't have the skills to install a python software.
For developers, most of them are using a virtualenv, and should not be a problem to install Python 3.
If all necessaries dependencies are available in Python 3 there is no reason to stay with Python 2.

**Comment by vbuterin** [comment]
So, python packages generally don't come with "installers". The process is
either:

1. sudo apt-get install python-pip
2. pip install pyethereum

Or:

1. git clone http://github.com/ethereum/pyethereum
2. cd pyethereum
3. sudo python setup.py install

That's the standard thing process that works with just about every python
package. If we make it any different from this, we lose a substantial
portion of users.

Also, plenty of people are still writing their code in python2. So, if they
have to switch over their entire architecture to py3 in order to use any
part of the pyethereum library code, then once again we lose users.

So, my general preference right now would be using six and trying to
maximally support both if we can. We've done it successfully with
pybitcointools; it passes all tests with py2, py3 and pypy right now.

**Comment by frewsxcv** [comment]
> So, python packages generally don't come with "installers". The process is either:

pip is bundled with Python starting in 2.7.9

**Comment by adamkrellenstein** [comment]
@vbuterin, the only people that are using `pip` or `git` are developers (not users), who of course should have no problem distinguishing between Python 2 and Python 3. Moreover, there's no problem with explicitly writing `pip3` and `python3` in all of the install instructions. That's what all new Python projects do, Counterparty included.

With regard to your second point, pyethereum is still in the proof-of-concept stage and obviously no production code depends on it. There aren't any projects that will have to switch over their architecture, and no one should be writing *new* code in Python 2. "*Python 2.x is legacy, Python 3.x is the present and future of the language*" (https://wiki.python.org/moin/Python2orPython3)

**Comment by pjdelport** [comment]
These are the currently open Python 3 PRs, just for easy reference: #238, #254, #329, #347.

#238 is big, while the other three are relatively small: would it be better to work toward getting #238 updated and merged first, or to try and fold the other three branches back into #238 first?

**Comment by pipermerriam** [comment]
I believe https://github.com/ethereum/pyethereum/pull/357 is ready for review and should close this issue.

**Comment by ofek** [comment]
@pipermerriam @vbuterin @joeykrug @heikoheiko Can this be closed?
