### ISSUE TITLE
pyethereum tutorial

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#159]
how/where to use pyeth and pyethclient to connect to the network, get address state, push transactions, etc

**Comment by heikoheiko** [comment]
See Ken's tutorials for a start:
https://dappsforbeginners.wordpress.com/2014/10/14/sub-currency-to-rainbow-coin/

**Comment by o-jasper** [comment]
Says it is private for me.

**Comment by danpdraper** [comment]
This might warrant a new ticket, but the broader problem stems from the pyethereum tutorial, so I will post the issue here for now. I get a TypeError when trying to call c.double(42) from a Python shell (per the pyethereum tutorial). I've attached a screenshot of my console with the commands that I entered along with the error. I also attached a screenshot showing the output of pip freeze in the virtual environment in which I've installed serpent and pyethereum. Whoever decides to take this on, let me know if you need anything else.

![contract_run](https://cloud.githubusercontent.com/assets/8284114/6261798/e99a6ee4-b7b2-11e4-827e-3c37b346afcf.png)

![pip_freeze](https://cloud.githubusercontent.com/assets/8284114/6261801/ef6cc628-b7b2-11e4-9168-770ad06de581.png)

**Comment by ridwannaibi** [comment]
After installing pythereum and ethereum serpent, I ran a test using:  pytest -m test_contracts.py
 I got the following error, and I can't seem to figure out what the real issue is:

![image](https://cloud.githubusercontent.com/assets/7573420/17871980/fdc05a4a-68b5-11e6-8c31-d587306b7392.png)

**Comment by utzig** [comment]
@ridwannaibi The correct syntax for running `pytest` is either:

`python -m pytest test_contracts.py`

or:

`pytest test_contracts.py`

**Comment by ridwannaibi** [comment]
@utzig 

 My bad I used 

`pytest test_contracts.py` 


And I am not face with new set of errors

`x = '\ndef main(a,b):\n    return(a ^ b)\n'

>   compile = lambda x: pyext.compile(x)
E   Exception: Error (file "main", line 2, char 12): Not a function or opcode: def

/usr/local/lib/python2.7/site-packages/ethereum_serpent-1.6.7-py2.7-macosx-10.11-x86_64.egg/EGG-INFO/scripts/serpent.py:74: Exception
----------------------------- Captured stderr call -----------------------------
`

**Comment by ridwannaibi** [comment]
@utzig 

I managed to solve it by doing what was recommended here [https://forum.ethereum.org/discussion/3422/error-with-pyethereum-abi-contract-importing-serpent-not-a-function-or-opcode-def](url), which as just by updating ethereum-serpent. Error seems to be from the specific version 1.6.7
