### ISSUE TITLE
Implementation of EIP106 breaks state tests

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/pyethereum#390]
See here: https://travis-ci.org/ethereum/pyethereum/jobs/143355805#L472-L553

EIP 106 was implemented in 03e1c889f41bf833a85a8daab8a916e254df8182

[`ethereum/testutils.py:run_state_tests`](https://github.com/ethereum/pyethereum/blob/develop/ethereum/testutils.py#L144) expects to create a `Block` object, even from invalid data. Therefore the current implementation of EIP 106 (raising a `ValueError` when `__init__`ializing with a too high `gas_limit`) is not compatible with the test function.

**Comment by konradkonrad** [comment]
@heikoheiko any advise on this one?

**Comment by heikoheiko** [comment]
https://github.com/ethereum/tests/blob/develop/StateTests/RandomTests/st201504011547GO.json
I'd say above test is invalid as it tests a state transition. The EIP106 requirements should be tested in a blocktest. 

Above test asserts that an OOG exception is triggered. 

As a hotfix I'd propose here to:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/testutils.py#L142
`gas_limit=min(2**64-1, parse_int_or_hex(env['currentGasLimit']))`
and then set `blk.gas_limit = parse_int_or_hex(env['currentGasLimit'])` after the constructor.

But again, I think the actual error is with above state test, because it depends on a block prestate which is out of bounds.

**Comment by winsvega** [comment]
you mean current gasLimit that is out of bounds? 
"currentGasLimit" : "115792089237316195423570985008687907853269984665640564039457584007913129639935",

**Comment by heikoheiko** [comment]
yes

**Comment by konradkonrad** [comment]
thanks @heikoheiko , this works. 
@winsvega should I create an issue at `ethereum/tests`?

**Comment by winsvega** [comment]
Yes we could just fix the gasLimit to fit new requirements. 
this test was auto-generated before we implemented this restriction.

**Comment by konradkonrad** [comment]
I think this is not relevant anymore
