### ISSUE TITLE
sha3 import aliasing not working 

### ISSUE THREAD

**Issue by miohtama** [ethereum/pyethereum#421]
I tried to run the unit tests for my `pyethereum` based project on Travis CI. They fail with an internal assert in `utils.py`:
 
       assert encode_hex(sha3(b'')) == b'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
      AssertionError

@chfast was kind and pointed me this might be because of incompatible `sha3` library.

I see in the head of `utils.py`

    try:
        from Crypto.Hash import keccak
        sha3_256 = lambda x: keccak.new(digest_bits=256, data=x).digest()
    except:
        import sha3 as _sha3
    sha3_256 = lambda x: _sha3.sha3_256(x).digest()

I am assuming I have wrong crypto library installed. However it is not hard failing during imports, because of this import aliasing. To make it more clear to the library user what is failing here I propose

* Either remove import aliasing for `sha3`

* Have an `assert` error message state "You are missing library install x"

**Comment by pipermerriam** [comment]
The error is actually caused from this commit upstream in pyrlp

https://github.com/ethereum/pyrlp/commit/2ec0fe159652f2cf12794bd8c239a8823cf93579#diff-08365a27b3d167a1798206d64f6e3708

The return value is not a string (instead of bytes).

**Comment by pipermerriam** [comment]
You can side-step this by forcing `rlp==0.4.6`

**Comment by ulope** [comment]
Actually turns out there is now another problem that triggers this.

`sha3` and `keccak` (although in principle the same algorithm) use slightly different padding strategies.

Ethereum [uses the keccak version](https://github.com/ethereum/wiki/wiki/Ethash#definitions).

Recently `pysha3` released v. 1.0.0 and in doing so switched to the 'standard' SHA3 implementation. They still provide a keccak implementation under the `keccak_256` name.

I've opened #430 to track this problem.
