### ISSUE TITLE
UPDATE PYPI PACKAGE

### ISSUE THREAD

**Issue by SerpentChris** [ethereum/pyethereum#436]
FIX the package on PyPI already! It's been broken for python 3 because of a single PRINT STATEMENT. Come on! Put the latest development code on PyPI please!

Making projects which depend on this is SUPER annoying because you can't simply put the dependency into a requirements.txt file, you have to manually clone the repo with git and install from that.

PLS PLS PLS fix this.

**Comment by konradkonrad** [comment]
Hey @SerpentChris ! Thanks for the friendly reminder :)
Can you explain what PRINT STATEMENT you're talking about? As you can see, the develop build is currently broken (at least due to upstream `solc` breaking changes, see #432 and https://travis-ci.org/ethereum/pyethereum/builds/204976053). I hope you understand that the minimum requirement for a release should be a working CI build/tests.

In the meantime, if you're having trouble with the [sanity check assertion for sha3 that you found](https://github.com/ethereum/pyethereum/pull/426), you *may* be able to work around your issue temporarily by explicitly requiring `pyrlp<=0.4.6` in your `requirements.txt`, until a new release is ready.

**Comment by SerpentChris** [comment]
Here is a screenshot:


<img width="1920" alt="screen shot 2017-03-01 at 12 31 35 pm" src="https://cloud.githubusercontent.com/assets/23585527/23479989/2ec6a4e0-fe7b-11e6-8c52-7979502da33b.png">

**Comment by SerpentChris** [comment]
Ohh my bad I put this issue in the wrong repository! heh...
>.>

**Comment by konradkonrad** [comment]
> I put this issue in the wrong repository

alright then :)
